name: Release Tagging

on:
  push:
    branches: [main]

permissions:
  contents: write  # allow downstream workflow to push tags

jobs:
  test:
    uses: draftm0de/flutter/.github/workflows/test.yml@main